#############################################################################################################
# Maintainer: Samir Elsayed <sel@plista.com> & Philipp Hoffmann <ph@plista.com>
#
# This pipeline consists of the following stages:
#
# - test (triggered by pushing changes to any branch)
# - package (triggered by pushing changes to master/tags)
#
##############################################################################################################

stages:
  - test
  - package

##############################################################################################################
# Active Jobs - when desired, they can be deactivated by placing a dot in front of the job name
##############################################################################################################
test:
  image: maven:3-jdk-8
  stage: test
  services:
    - redis
  script:
    - mvn test -DredisHost=redis

package:
  image: maven:3-jdk-8
  stage: package
  only:
    - master
    - tags
    - plista-changes
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: '1 week'
